container:
  image: python:latest

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION #&& cat setup.cfg
    populate_script: pip install -e .[testing]
  test_script: py.test
