language: python
notifications:
  email: false
python:
  - "3.9"
install:
  - pip install -e .[testing]
  - pip install coveralls
script:
  - py.test
after_success:
  - coveralls
deploy:
  provider: pypi
  username: "__token__"
  password: ${{ secrets.PYPI_TOKEN }}
  on:
    tags: true
